= Declarative Annotations in Eclipse Neon [DRAFT] =

== Motivation ==
Many Eclipse RCP applications are using OSGi Services make their application leightweight and flexible. The most convient method is to use OSGi Services in combination with Declarative Services. This allows to specifiy OSGi Services by XML files. Why this can be quite convient can be found here http://www.vogella.com/tutorials/OSGiServices/article.html#declarativeservices[DS@Vogella]. Before Eclipse Neon there were two possibilities to edit these XML files.

Before Eclipse Neon there were two possibilties to create or modify these XML files. 

. By Hand - Disadvantage: Error prone. 
. Integration editor - Disadvantages: Error prone on re-factoring, no consistent naming scheme.

No Eclipse Neon integrated a third solution: Generation of XML files by code annotations. In this blog I want to show more detailled how this can work. 

== Code Example ==

Expecting a simple HelloWorld OSGi application, with 

* a HelloWorldService and
* a HelloWorldClient.

The HelloWorldService is exporting following simple interface.

[source,java]
----
package my.osgi.ds.example.helloservice.api;

public interface HelloWorldService {
    // Prints 'Hello + name' to the console
    public void sayHello(String name);
}
----

Whenever `sayHello` is called 'Hello + name' is printed on the console. 

Here is the corresponding implmentation of this OSGi Service. So the implementation is quite straight forward. 
Now let us come to the interesting part of this class - the `@Component` DS Annotations. 
[source,java]
----
package my.osgi.ds.example.helloservice.impl;

import org.osgi.service.component.annotations.Component;
import my.osgi.ds.example.helloservice.api.HelloWorldService;

@Component
public class HelloWorldServiceImpl implements HelloWorldService {

	@Override
	public void sayHello(String name) {
		System.out.println(("Hello " + name + "!"));
	}

}
----
To register a class as OSGi-Service (Component is used here as synonym) just use `@Component` as class annotation. That's the minimum to register a class as OSGi service. If you save this class automatically a new XML file `my.osgi.ds.example.helloservice.impl.HelloWorldServiceImpl.xml` will be generated `OSGI-INF`. 
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="my.osgi.ds.example.helloservice.impl.HelloWorldServiceImpl">
   <service>
      <provide interface="my.osgi.ds.example.helloservice.api.HelloWorldService"/>
   </service>
   <implementation class="my.osgi.ds.example.helloservice.impl.HelloWorldServiceImpl"/>
</scr:component>
----
So in the most cases this should be enough. Look's quite easy. 


=== HelloWorldClient ===

[source,java]
----
package my.osgi.ds.example.helloclient.impl;

import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import my.osgi.ds.example.common.DebugOutputHelper;
import my.osgi.ds.example.helloservice.api.HelloWorldService;

@Component
public class HelloWorldClientImpl {

	private HelloWorldService helloWorldService;

	public HelloWorldClientImpl() {
		DebugOutputHelper.logConstructor(getClass());
	}

	@Activate <1>
	public void start() {
		DebugOutputHelper.logStart(getClass());

		helloWorldService.sayHello("Mr. X");
	}

	@Reference(unbind = "unbind") <2>
	public void bind(HelloWorldService helloWorldService) {
		DebugOutputHelper.logBind(getClass(), helloWorldService.getClass());

		this.helloWorldService = helloWorldService;
	}

	public void unbind(HelloWorldService helloWorldService) {
		DebugOutputHelper.logUnbind(getClass(), helloWorldService.getClass());

		this.helloWorldService = null;
	}

	@Deactivate <3>
	public void stop() {
		DebugOutputHelper.logStop(getClass());
	}
}

----
<1> Activation method
<2> OSGi Service Reference
<3> Deactivation method

